---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: mixed-line-ending
- repo: https://github.com/commitizen-tools/commitizen
  rev: 3.10.0
  hooks:
  - id: commitizen
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    language_version: python3.11
- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
  - id: interrogate
    args: [--quiet, --fail-under=95]
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.32.0
  hooks:
  - id: yamllint
    args: [-s, -c=.yamllint]
